// data/products.js
export const products = [
  {
      "id": "1",
      "name": "Khóa học React",
      "price": 450000,
      "category": "Web Development",
      "description": "React cơ bản đến nâng cao",
      "longDescription": "Chi tiết JSX, Hooks, Router và thực hành dự án",
      "image": "https://placehold.co/300x200?text=React",
      "rating": 4.5,
      "isHot": true,
      "isNew": false,
      "createdAt": "2023-01-15T10:00:00Z"
    },
    {
      "id": "2",
      "name": "Tiếng Anh với người bản xứ",
      "price": 1200000,
      "category": "Language",
      "description": "Luyện nói tiếng Anh",
      "longDescription": "Luyện phản xạ và phát âm chuẩn",
      "image": "https://placehold.co/300x200?text=English",
      "rating": 5,
      "isHot": true,
      "isNew": true,
      "createdAt": "2023-02-20T12:00:00Z"
    },
    {
      "id": "3",
      "name": "Khóa học Node.js",
      "price": 600000,
      "category": "Backend Development",
      "description": "Backend chuyên sâu",
      "longDescription": "Xây dựng REST API, Express, MongoDB",
      "image": "https://placehold.co/300x200?text=Node.js",
      "rating": 4.2,
      "isHot": false,
      "isNew": false,
      "createdAt": "2023-03-10T14:00:00Z"
    },
    {
      "id": "4",
      "name": "Khóa học UI/UX Design",
      "price": 700000,
      "category": "Design",
      "description": "Thiết kế trải nghiệm người dùng",
      "longDescription": "Figma, nguyên lý thiết kế, thiết kế ứng dụng web/mobile",
      "image": "https://placehold.co/300x200?text=UI%2FUX",
      "rating": 4.8,
      "isHot": true,
      "isNew": true,
      "createdAt": "2023-04-05T16:00:00Z"
    },
    {
      "id": "5",
      "name": "Khóa học Vue.js",
      "price": 490000,
      "category": "Web Development",
      "description": "Vue từ cơ bản đến nâng cao",
      "longDescription": "Vue CLI, Vue Router, Vuex, Composition API",
      "image": "https://placehold.co/300x200?text=Vue",
      "rating": 4.3,
      "isHot": false,
      "isNew": true,
      "createdAt": "2023-05-15T18:00:00Z"
    },
    {
      "id": "6",
      "name": "Tiếng Nhật sơ cấp",
      "price": 800000,
      "category": "Language",
      "description": "Giao tiếp tiếng Nhật cơ bản",
      "longDescription": "Học từ vựng, ngữ pháp, nghe hiểu và hội thoại sơ cấp",
      "image": "https://placehold.co/300x200?text=Japanese",
      "rating": 4.6,
      "isHot": false,
      "isNew": true,
      "createdAt": "2023-06-01T20:00:00Z"
    },
    {
      "id": "7",
      "name": "Khóa học Python",
      "price": 350000,
      "category": "Programming",
      "description": "Python cho người mới bắt đầu",
      "longDescription": "Cấu trúc dữ liệu, vòng lặp, hàm và project mini",
      "image": "https://placehold.co/300x200?text=Python",
      "rating": 4.7,
      "isHot": false,
      "isNew": false,
      "createdAt": "2023-07-10T22:00:00Z"
    },
    {
      "id": "8",
      "name": "Khóa học Data Science",
      "price": 1500000,
      "category": "Data Science",
      "description": "Phân tích dữ liệu và học máy",
      "longDescription": "Pandas, NumPy, Scikit-learn, dự án thực tế",
      "image": "https://placehold.co/300x200?text=Data+Science",
      "rating": 4.9,
      "isHot": true,
      "isNew": false,
      "createdAt": "2023-08-20T10:00:00Z"
    },
    {
      "id": "9",
      "name": "Khóa học IELTS 7.0+",
      "price": 1350000,
      "category": "Language",
      "description": "Luyện thi IELTS chuyên sâu",
      "longDescription": "Chiến lược làm bài Reading, Writing, Speaking hiệu quả",
      "image": "https://placehold.co/300x200?text=IELTS",
      "rating": 5,
      "isHot": true,
      "isNew": true,
      "createdAt": "2023-09-15T12:00:00Z"
    },
    {
      "id": "10",
      "name": "Khóa học Excel chuyên sâu",
      "price": 400000,
      "category": "Office Skills",
      "description": "Excel từ cơ bản đến nâng cao",
      "longDescription": "Hàm, Pivot Table, Dashboard, VBA",
      "image": "https://placehold.co/300x200?text=Excel",
      "rating": 4.4,
      "isHot": false,
      "isNew": false,
      "createdAt": "2023-10-01T14:00:00Z"
    },
    {
      "id": "11",
      "name": "Kỹ năng thuyết trình",
      "price": 300000,
      "category": "Soft Skills",
      "description": "Tăng sự tự tin khi nói trước đám đông",
      "longDescription": "Ngôn ngữ cơ thể, trình bày slide, xử lý câu hỏi",
      "image": "https://placehold.co/300x200?text=Presentation",
      "rating": 4.1,
      "isHot": false,
      "isNew": false,
      "createdAt": "2023-11-05T16:00:00Z"
    },
    {
      "id": "12",
      "name": "Tư duy phản biện",
      "price": 550000,
      "category": "Soft Skills",
      "description": "Cải thiện kỹ năng phân tích và đánh giá",
      "longDescription": "Thảo luận, phân tích tình huống, giải quyết vấn đề",
      "image": "https://placehold.co/300x200?text=Critical+Thinking",
      "rating": 4.6,
      "isHot": false,
      "isNew": true,
      "createdAt": "2023-12-01T18:00:00Z"
    }
];
